# agent基座模型的配置
llm: 
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1  # api提供商
  api_key: sk-your-llm-key # api key
  model_name: qwen3-next-80b-a3b-instruct # 模型名称
  output_streaming: false # 没有适配true，只做占位

# Langfuse相关配置，包括主机url、api key等
langfuse:
  host: https://cloud.langfuse.com
  public_key: pk-your-langfuse-public
  secret_key: sk-your-langfuse-secret
  release: dev
  enabled: true
  evaluator_name: null

# 是否使用长期存储
store:
  kind: sqlite # memory
  path: data/conversations.db

# 评测专用LLM等配置，字段同基座
eval_llm:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  api_key: sk-your-llm-key
  model_name: qwen3-next-80b-a3b-instruct
  output_streaming: false
